<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "minicleaner"
 *
 * Auto generated by Extension Builder 2015-07-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'MiniCleaner',
    'description' => 'Scheduler Task for deleting files in configurable folders',
    'category' => 'be',
    'author' => 'Sven Juergens',
    'author_email' => 't3YYYY@blue-side.de',
    'state' => 'stable',
    'version' => '3.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '11.5.30-11.9.99',
            'scheduler' => '11.5.30-11.9.999',
        ],
        'conflicts' => [
        ],
        'suggests' => [
        ],
    ],
];
