<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "minicleaner"
 *
 * Auto generated by Extension Builder 2015-07-09
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'MiniCleaner',
	'description' => 'Scheduler Task for deleting files in configurable folders',
	'category' => 'be',
	'author' => 'Sven Jürgens',
	'author_email' => 't3@blue-side.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 0,
	'version' => '1.0.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2.0-6.2.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);